### ISSUE TITLE
re-evaluate start up performance

### ISSUE THREAD

**Issue by bartvde** [MapStory/story-tools#125]
A map with a lot of layers, 172 e.g. http://localhost:8001/examples/full-example.html#172 is really slow on the initial load.

**Comment by bartvde** [comment]
I really think we should have a custom endpoint that gives us all needed info in one go.
Now every layer does: GetCapabilities (to get time info), DescribeFeatureType, get time field etc.

@ischneider what are your thoughts on this?

**Comment by bartvde** [comment]
playback performance also not acceptable currently

**Comment by ischneider** [comment]
I think what we should do is story as much as possible with the layer and allow the user to refresh when needed (for example, to update time extents if they change). This way the cost is incurred when adding a layer.

For importing old config, if we do it on the client (versus some server-side transformation), we need to provide some progress indication.

FYI - I got an error that params were undefined on that map (172) from MapManager#116 (`var params = layer.args[2];`) but I witnessed the slowness on another map.

**Comment by ischneider** [comment]
You probably addressed this w/ #126 ...

**Comment by bartvde** [comment]
right #126 should fix that once merged I ran into it as well today

**Comment by bartvde** [comment]
@ischneider so can I assume the following:

* layer info page will have all this information cached (when is it cached, when somebody uploads a dataset to MapStory I guess?)
* the backend will support getting layer info for multiple layers in one go?
* the layer info page will allow the user to refresh the cached info?
* this data will not be saved inside of the map config right?

**Comment by ischneider** [comment]
> @ischneider so can I assume the following:
> 
>     layer info page will have all this information cached (when is it cached, when somebody uploads a dataset to MapStory I guess?)

For a layer page, it seems less critical since it's just one layer but ideally yes. There is some attribute caching on the GeoNode side but not what we need.

>     the backend will support getting layer info for multiple layers in one go?

I don't think so. Working around this by caching.

>     the layer info page will allow the user to refresh the cached info?

Ideally yes. As noted, there is attribute caching in GeoNode and this can currently get stale.

>     this data will not be saved inside of the map config right?

My thought is this is exactly where it gets saved.

**Comment by bartvde** [comment]
okay so your intention is to have it saved in the map config?
If a layer's time values change, people will need to go to all saved maps and update them?

**Comment by ischneider** [comment]
I agree it's not ideal but also consider a story that involves a fixed extent within a layer. Perhaps the layer updates regularly but the story composer is not interested in the new data (or wasn't aware the layer would be updated). An example might be contrasting two layers with an overlapping, but not equal temporal extent. Automatically updating the extents would also not be expected behavior (one layer now has 10 additional steps the other one does not cover)

This makes me think the behavior should be configurable at least but defaulting to the cached behavior.

The other potential way to mitigate the capabilities cost is using `interval` instead of `list` as often data is truly best represented this way but this doesn't address the case when `list` behavior is required.

**Comment by bartvde** [comment]
The approach was changed. So closing for now.
